import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
           input: [
                'resources/sass/app.scss',
                'resources/css/dashboard.css',
                'resources/css/categorias.css',
                'resources/css/atributos.css',
                'resources/css/productos.css',
                'resources/css/sucursales.css',
                'resources/css/almacenes.css',
                'resources/css/proveedores.css',
                'resources/css/clientes.css',
                'resources/css/ordenes_compra.css',
                'resources/css/usuarios.css',
                'resources/css/inventario.css',
                'resources/css/ajustes.css',
                'resources/css/comprobantes.css',
                'resources/css/descuentos.css',
                'resources/css/ventas.css',
                'resources/js/app.js',
                'resources/js/dashboard.js',
                'resources/js/categorias.js',
                'resources/js/atributos.js',
                'resources/js/productos.js',
                'resources/js/sucursales.js',
                'resources/js/almacenes.js',
                'resources/js/proveedores.js',
                'resources/js/clientes.js',
                'resources/js/ordenes_compra.js',
                'resources/js/recepciones.js',
                'resources/js/usuarios.js',
                'resources/js/empleados.js',
                'resources/js/inventario.js',
                'resources/js/movimientos.js',
                'resources/js/ajustes.js',
                'resources/js/tipos_pago.js',
                'resources/js/comprobantes.js',
                'resources/js/descuentos.js',
                'resources/js/ventas.js',
            ],
            refresh: true,
        }),
    ],
});